### ISSUE TITLE
Support for MBD

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/dftbplus-feedstock#6]
Issue:
- support for MBD in DFTB+ conda-forge package (`WITH_MBD` option)
- requires [`libmbd`](https://github.com/conda-forge/libmbd-feedstock) dependency:
```yaml
requirements:
  host:
    - libmbd
    - libmbd * mpi_{{ mpi }}_*  # [ mpi != "nompi ]
  run:
    - pin_compatible('libmbd', max_pin('x.x'))  # [ mpi == "nompi" ]
    - pin_compatible('libmbd', max_pin('x.x')) mpi_{{ mpi }}_*  # [ mpi != "nompi" ]
```
