### ISSUE TITLE
Support for transport

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/dftbplus-feedstock#7]
Issue:
- support for transport in DFTB+ conda-forge package (`WITH_TRANSPORT` option)
- requires [`libnegf`](https://github.com/conda-forge/libnegf-feedstock) dependency:
```yaml
requirements:
  host:
    - libnegf
    - libnegf * mpi_{{ mpi }}_*  # [ mpi != "nompi ]
  run:
    - pin_compatible('libnegf', max_pin('x.x'))  # [ mpi == "nompi" ]
    - pin_compatible('libnegf', max_pin('x.x')) mpi_{{ mpi }}_*  # [ mpi != "nompi" ]
```
